In [1]:
import numpy as np

In [21]:
# 1. 导入鸢尾属植物数据集，保持文本不变
iris = np.genfromtxt('./iris.csv',delimiter=',', skip_header=1, usecols=(0,1,2,3))
iris[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [25]:
#2. 求出鸢尾属植物萼片长度的平均值、中位数和标准差（第1列，sepallength
print(np.mean(iris, axis=0)[0])   #平均值
print(np.median(iris, axis=0)[0]) #中位数 
print(np.std(iris, axis=0)[0])    #标准差

5.843333333333335
5.8
0.8253012917851409


In [28]:
#3. 创建一种标准化形式的鸢尾属植物萼片长度，其值正好介于0和1之间，这样最小值为0，最大值为1（第1列，sepallength）
# 0， 1标准化
min_sepallength = np.min(iris, axis=0)[0]
max_sepallength  = np.max(iris, axis=0)[0]
std = (iris[:, 0] - min_sepallength)/max_sepallength
print(std)

In [29]:
#4.找到鸢尾属植物萼片长度的第5和第95百分位数（第1列，sepallength）
np.percentile(iris[:, 0], [5, 95])

array([4.6  , 7.255])

In [35]:
#5. 把iris_data数据集中的20个随机位置修改为np.nan值
indexes = list(set(np.random.randint(low=0, high = 150, size = 30)))[0:20]
col1 = iris[:, 0]
col1[indexes] = np.nan

In [37]:
#6. 在iris_data的sepallength中查找缺失值的个数和位置（第1列）
nan_index = np.argwhere(np.isnan(col1))
print(nan_index)
print(nan_index.shape)

[[  1]
 [ 11]
 [ 22]
 [ 25]
 [ 28]
 [ 30]
 [ 32]
 [ 36]
 [ 37]
 [ 38]
 [ 40]
 [ 49]
 [ 56]
 [ 59]
 [ 61]
 [ 65]
 [ 71]
 [132]
 [135]
 [137]]
(20, 1)


In [41]:
#7. 筛选具有 sepallength（第1列）< 5.0 并且 petallength（第3列）> 1.5 的 iris_data行
value = iris[(iris[:, 1]<5)&(iris[:, 2]<1.5)]
value.shape

(24, 4)

In [55]:
#8. 选择没有任何 nan 值的 iris_data行
iris1 = iris[~np.isnan(iris[:, 0])]
iris1.shape

(130, 4)

In [56]:
#9. 计算 iris_data 中sepalLength（第1列）和petalLength（第3列）之间的相关系数
score = np.corrcoef(iris1[:, 0], iris1[:, 2])
print(score)

[[1.         0.86319659]
 [0.86319659 1.        ]]


In [57]:
# 10. 找出iris_data是否有任何缺失值
np.isnan(iris)

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
 

In [60]:
#11. 在numpy数组中将所有出现的nan替换为0。
iris[np.isnan(iris)]=0

In [63]:
#12. 找出鸢尾属植物物种中的唯一值和唯一值出现的数量
print(np.unique(iris))
print(len(np.unique(iris)))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
75


In [68]:
#13. 将 iris_data 的花瓣长度（第3列）以形成分类变量的形式显示。定义：Less than 3 --> ‘small’；3-5 --> ‘medium’；’>=5 --> ‘large’
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5])
label_map = {1: 'small', 2: 'medium', 3: 'large'}
petal_length_cat = [label_map[x] for x in petal_length_bin]

In [75]:
# 14. 在 iris_data 中创建一个新列，其中 volume 是 (pi x petallength x sepallength ^ 2）/ 3
b = np.pi*iris[:, 0]*(iris[:, 3]*iris[:, 3])/3
iris_new = np.insert(iris, 4, values=b, axis=1)
print(iris)

In [87]:
#15. 随机抽鸢尾属植物的种类，使得Iris-setosa的数量是Iris-versicolor和Iris-virginica数量的两倍。
x = np.random.hypergeometric(ngood=50, nbad=100, nsample=21, size=21)
x

array([ 4,  8, 11,  9,  7,  8,  9,  6,  7,  4,  4,  5,  6,  5,  8,  9, 10,
        3,  9,  8,  6])

In [85]:
#16. 根据 sepallength 列对数据集进行排序
iris2 = iris[iris[:,0].argsort()]
print(iris2)

[[0.  3.6 1.  0.2]
 [0.  3.  1.6 0.2]
 [0.  3.1 1.6 0.2]
 [0.  2.8 5.6 2.2]
 [0.  3.1 5.5 1.8]
 [0.  3.3 4.7 1.6]
 [0.  4.1 1.5 0.1]
 [0.  2.7 3.9 1.4]
 [0.  3.3 1.4 0.2]
 [0.  3.  4.2 1.5]
 [0.  3.1 4.4 1.4]
 [0.  3.5 1.3 0.2]
 [0.  3.  6.1 2.3]
 [0.  2.8 4.  1.3]
 [0.  3.6 1.4 0.1]
 [0.  3.4 1.6 0.2]
 [0.  3.  1.3 0.2]
 [0.  3.5 1.3 0.3]
 [0.  3.  1.4 0.2]
 [0.  3.4 1.4 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.  1.4 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.2]
 [4.9 2.5 4.5 1.7]
 [4.9 3.1 1.5 0.1]
 [5.  2.  3.5 1. ]
 [5.  3.2 1.2 0.2]
 [5.  3.4 1.5 0.2]
 [5.  2.3 3.3 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.6 0.2]
 [5.1 2.5 3.  1.1]
 [5.1 3.5 1.4 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.3 1.7 0.5]
 [5.1 3.8 1.9 0.4]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.5 0.3]
 [5.2 3.5 1.

In [78]:
#17. 在鸢尾属植物数据集中找到最常见的花瓣长度值（第3列）
from collections import Counter
a = iris[:, 2]
b = Counter(a)
print(b.most_common(1))

[(1.4, 13)]


In [82]:
#18. 在鸢尾花数据集的 petalwidth（第4列）中查找第一次出现的值大于1.0的位置
np.arange(len(iris[:, 3] ))[iris[:, 3] > 1][0]

50