In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])
z = np.dot(x, y)
print(z)

70


In [3]:
x = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
print(x)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [4]:
y = np.array([[5, 4, 2], [1, 7, 9], [0, 4, 5]])
print(y)

[[5 4 2]
 [1 7 9]
 [0 4 5]]


In [5]:
z = np.dot(y, x)
print(z)

[[ 29  40  51]
 [ 76  93 110]
 [ 42  51  60]]


In [6]:
x = np.diag((1, 2, 3))
print(x)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [8]:
print(np.linalg.eigvals(x))

[1. 2. 3.]


In [9]:
a, b = np.linalg.eig(x)
print(a)
print(b)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
for i in range(3):
    if np.allclose(a[i]*b[:, i], np.dot(x, b[:, i])):
        print('Right')
    else:
        print('Error')

Right
Right
Right


In [11]:
import numpy as np
A = np.arange(16).reshape(4, 4)
print(A)

A = A + A.T
print(A)

B = np.linalg.eigvals(A)
print(B)

if np.all(B > 0):
    print('Yes')
else:
    print('No')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
[ 6.74165739e+01 -7.41657387e+00  1.82694656e-15 -1.72637110e-15]
No


In [15]:
import numpy as np
A = np.array([[4, 11, 14], [8, 7, -2]])
print(A)

u, s, vh = np.linalg.svd(A, full_matrices=False)
print(u.shape)
print(u)

print(s.shape)
print(np.diag(s))

print(vh.shape)
print(vh)

a = np.dot(u, np.diag(s))
a = np.dot(a, vh)
print(a)

[[ 4 11 14]
 [ 8  7 -2]]
(2, 2)
[[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
(2,)
[[18.97366596  0.        ]
 [ 0.          9.48683298]]
(2, 3)
[[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]
[[ 4. 11. 14.]
 [ 8.  7. -2.]]


In [16]:
import numpy as np
A = np.array([[1, 1], [1, -2], [2, 1]])
print(A)

u, s, vh = np.linalg.svd(A, full_matrices=False)
print(u.shape)
print(u)

print(s.shape)
print(np.diag(s))

print(vh.shape)
print(vh)

[[ 1  1]
 [ 1 -2]
 [ 2  1]]
(3, 2)
[[-5.34522484e-01 -1.11022302e-16]
 [ 2.67261242e-01 -9.48683298e-01]
 [-8.01783726e-01 -3.16227766e-01]]
(2,)
[[2.64575131 0.        ]
 [0.         2.23606798]]
(2, 2)
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [17]:
import numpy as np

A = np.array([[2, -2, 3], [1, 1, 1], [1, 3, -1]])
print(A)

q, r = np.linalg.qr(A)
print(q.shape)
print(q)

print(r.shape)
print(r)

print(np.dot(q, r))

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]
(3, 3)
[[-0.81649658  0.53452248  0.21821789]
 [-0.40824829 -0.26726124 -0.87287156]
 [-0.40824829 -0.80178373  0.43643578]]
(3, 3)
[[-2.44948974  0.         -2.44948974]
 [ 0.         -3.74165739  2.13808994]
 [ 0.          0.         -0.65465367]]
[[ 2. -2.  3.]
 [ 1.  1.  1.]
 [ 1.  3. -1.]]


In [23]:
import numpy as np

x = np.array([1, 2, 3, 4])
print(np.linalg.norm(x, ord=1))
print(np.sum(np.abs(x)))

print(np.linalg.norm(x, ord=2))
print(np.sum(np.abs(x) ** 2) ** 0.5)

print(np.linalg.norm(x, ord=-np.inf))  
# 1.0
print(np.min(np.abs(x)))

print(np.linalg.norm(x, ord=np.inf))  
# 4.0
print(np.max(np.abs(x)))

10.0
10
5.477225575051661
5.477225575051661
1.0
1
4.0
4


In [24]:
A = np.array([[1, 2, 3, 4], [2, 3, 5, 8], [1, 3, 5, 7], [3, 4, 7, 11]])
print(A)

print(np.linalg.norm(A, ord=1))
print(np.max(np.sum(A, axis=0)))

print(np.linalg.norm(A, ord=2))
print(np.max(np.linalg.svd(A, compute_uv=False)))

print(np.linalg.norm(A, ord=np.inf))
print(np.linalg.norm(A, ord='fro'))

print(np.sqrt(np.trace(np.dot(A.T, A))))

[[ 1  2  3  4]
 [ 2  3  5  8]
 [ 1  3  5  7]
 [ 3  4  7 11]]
30.0
30
20.24345358700576
20.24345358700576
25.0
20.273134932713294
20.273134932713294


In [25]:
import numpy as np

A = np.array([[1, -2, 1], [0, 2, -1], [1, 1, -2]])
print(A)

A_det = np.linalg.det(A)  
print(A_det)

[[ 1 -2  1]
 [ 0  2 -1]
 [ 1  1 -2]]
-2.9999999999999996


In [26]:
A_inverse = np.linalg.inv(A)  # 求A的逆矩阵
print(A_inverse)

x = np.allclose(np.dot(A, A_inverse), np.eye(3))
print(x)  # True
x = np.allclose(np.dot(A_inverse, A), np.eye(3))
print(x) 

[[ 1.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 3.33333333e-01  1.00000000e+00 -3.33333333e-01]
 [ 6.66666667e-01  1.00000000e+00 -6.66666667e-01]]
True
True


In [27]:
import numpy as np

A = np.array([[1, 2, 1], [2, -1, 3], [3, 1, 2]])
b = np.array([7, 7, 18])
x = np.linalg.solve(A, b)
print(x)  # [ 7.  1. -2.]

x = np.linalg.inv(A).dot(b)
print(x)  # [ 7.  1. -2.]

y = np.allclose(np.dot(A, x), b)
print(y) 

[ 7.  1. -2.]
[ 7.  1. -2.]
True
