In [2]:
# 计算最小值
import numpy as np
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.amin(x)
print(y)

y = np.amin(x, axis=0) #返回每列的最小值
print(y)

y = np.amin(x, axis=1) #返回每行的最小值
print(y)

11
[11 12 13 14 15]
[11 16 21 26 31]


In [3]:
#计算最大值

y = np.amax(x)
print(y)

y = np.amax(x, axis=0) # 返回每列的最大值
print(y)

y = np.amax(x, axis=1) # 返回每行的最大值
print(y)

35
[31 32 33 34 35]
[15 20 25 30 35]


In [4]:
#计算极值
np.random.seed(20200623)
x = np.random.randint(0, 20, size=[4, 5])
print(x)

print(np.ptp(x))
print(np.ptp(x, axis=0)) # 返回每列的极值
print(np.ptp(x, axis=1)) # 返回每行的极值

[[10  2  1  1 16]
 [18 11 10 14 10]
 [11  1  9 18  8]
 [16  2  0 15 16]]
18
[ 8 10 10 17  8]
[15  8 17 16]


In [5]:
# 计算分位数
np.random.seed(20200623)
x = np.random.randint(0, 20, size=[4, 5])
print(x)

print(np.percentile(x, [25, 50]))  


print(np.percentile(x, [25, 50], axis=0))

print(np.percentile(x, [25, 50], axis=1))

[[10  2  1  1 16]
 [18 11 10 14 10]
 [11  1  9 18  8]
 [16  2  0 15 16]]
[ 2. 10.]
[[10.75  1.75  0.75 10.75  9.5 ]
 [13.5   2.    5.   14.5  13.  ]]
[[ 1. 10.  8.  2.]
 [ 2. 11.  9. 15.]]


In [6]:
# 计算中位数
np.random.seed(20200623)
x = np.random.randint(0, 20, size=[4, 5])
print(x)
print(np.percentile(x, 50))
print(np.median(x))


print(np.percentile(x, 50, axis=0))
print(np.median(x, axis=0))

print(np.percentile(x, 50, axis=1))
print(np.median(x, axis=1))

[[10  2  1  1 16]
 [18 11 10 14 10]
 [11  1  9 18  8]
 [16  2  0 15 16]]
10.0
10.0
[13.5  2.   5.  14.5 13. ]
[13.5  2.   5.  14.5 13. ]
[ 2. 11.  9. 15.]
[ 2. 11.  9. 15.]


In [7]:
# 计算平均值
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.mean(x)
print(y)  

y = np.mean(x, axis=0)
print(y)  

y = np.mean(x, axis=1)
print(y) 

23.0
[21. 22. 23. 24. 25.]
[13. 18. 23. 28. 33.]


In [8]:
# 计算加权平均
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.average(x)
print(y)  # 23.0

y = np.average(x, axis=0)
print(y)  # [21. 22. 23. 24. 25.]

y = np.average(x, axis=1)
print(y)  # [13. 18. 23. 28. 33.]


y = np.arange(1, 26).reshape([5, 5])
print(y)

z = np.average(x, weights=y)
print(z)  # 27.0

z = np.average(x, axis=0, weights=y)
print(z)


z = np.average(x, axis=1, weights=y)
print(z)


23.0
[21. 22. 23. 24. 25.]
[13. 18. 23. 28. 33.]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
27.0
[25.54545455 26.16666667 26.84615385 27.57142857 28.33333333]
[13.66666667 18.25       23.15384615 28.11111111 33.08695652]


In [9]:
# 计算方差
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.var(x)
print(y)  
y = np.mean((x - np.mean(x)) ** 2)
print(y)  

y = np.var(x, ddof=1)
print(y)  
y = np.sum((x - np.mean(x)) ** 2) / (x.size - 1)
print(y)  

y = np.var(x, axis=0)
print(y)  

y = np.var(x, axis=1)
print(y)  

52.0
52.0
54.166666666666664
54.166666666666664
[50. 50. 50. 50. 50.]
[2. 2. 2. 2. 2.]


In [10]:
# 计算标准差
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.std(x)
print(y) 
y = np.sqrt(np.var(x))
print(y) 

y = np.std(x, axis=0)
print(y)


y = np.std(x, axis=1)
print(y)

7.211102550927978
7.211102550927978
[7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]
[1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]


In [11]:
#计算协方差举证
x = [1, 2, 3, 4, 6]
y = [0, 2, 5, 6, 7]
print(np.cov(x))  
print(np.cov(y))  
print(np.cov(x, y))


print(np.var(x))  # 2.96    
print(np.var(x, ddof=1))  
print(np.var(y))  # 6.8    
print(np.var(y, ddof=1)) 

z = np.mean((x - np.mean(x)) * (y - np.mean(y)))   
print(z)  # 4.2

z = np.sum((x - np.mean(x)) * (y - np.mean(y))) / (len(x) - 1)  
print(z)  # 5.25

z = np.dot(x - np.mean(x), y - np.mean(y)) / (len(x) - 1)      
print(z) 

3.7
8.5
[[3.7  5.25]
 [5.25 8.5 ]]
2.96
3.7
6.8
8.5
4.2
5.25
5.25


In [12]:
# 计算相关系数
np.random.seed(20200623)
x, y = np.random.randint(0, 20, size=(2, 4))

print(x)  
print(y)  

z = np.corrcoef(x, y)
print(z)


a = np.dot(x - np.mean(x), y - np.mean(y))
b = np.sqrt(np.dot(x - np.mean(x), x - np.mean(x)))
c = np.sqrt(np.dot(y - np.mean(y), y - np.mean(y)))
print(a / (b * c))  

[10  2  1  1]
[16 18 11 10]
[[1.         0.48510096]
 [0.48510096 1.        ]]
0.4851009629263671
